Code.require_file Path.expand("priv/repo/logradouros_search.ex"), __DIR__
defmodule StatesApi.Repo.LogradourosSearchTest do
  use ExUnit.Case
  alias StatesApi.Repo.LogradouroSearch

  test "build_readings" do
    logradouro = %{tipo: "Rua", nome: "Dom Pedro II", abbr: "R D Pedro II"}
    bairro = %{nome: "Centro", abbr: "Cen"}
    localidade = %{nome: "Foz do Iguacu", abbr: "Foz Iguacu"}
    estado = %{nome: "Parana", sigla: "PR"}

    readings = LogradouroSearch.build_readings(logradouro, bairro, localidade, estado)
    assert Enum.sort(readings) == Enum.sort(["dom pedro ii", "dom pedro ii cen", "dom pedro ii cen foz do iguacu", "dom pedro ii cen foz do iguacu parana", "dom pedro ii cen foz do iguacu pr", "dom pedro ii cen foz iguacu", "dom pedro ii cen foz iguacu parana", "dom pedro ii cen foz iguacu pr", "dom pedro ii cen parana", "dom pedro ii cen pr", "dom pedro ii centro", "dom pedro ii centro foz do iguacu", "dom pedro ii centro foz do iguacu parana", "dom pedro ii centro foz do iguacu pr", "dom pedro ii centro foz iguacu", "dom pedro ii centro foz iguacu parana", "dom pedro ii centro foz iguacu pr", "dom pedro ii centro parana", "dom pedro ii centro pr", "dom pedro ii foz do iguacu", "dom pedro ii foz do iguacu parana", "dom pedro ii foz do iguacu pr", "dom pedro ii foz iguacu", "dom pedro ii foz iguacu parana", "dom pedro ii foz iguacu pr", "dom pedro ii parana", "dom pedro ii pr", "r d pedro ii", "r d pedro ii cen", "r d pedro ii cen foz do iguacu", "r d pedro ii cen foz do iguacu parana", "r d pedro ii cen foz do iguacu pr", "r d pedro ii cen foz iguacu", "r d pedro ii cen foz iguacu parana", "r d pedro ii cen foz iguacu pr", "r d pedro ii cen parana", "r d pedro ii cen pr", "r d pedro ii centro", "r d pedro ii centro foz do iguacu", "r d pedro ii centro foz do iguacu parana", "r d pedro ii centro foz do iguacu pr", "r d pedro ii centro foz iguacu", "r d pedro ii centro foz iguacu parana", "r d pedro ii centro foz iguacu pr", "r d pedro ii centro parana", "r d pedro ii centro pr", "r d pedro ii foz do iguacu", "r d pedro ii foz do iguacu parana", "r d pedro ii foz do iguacu pr", "r d pedro ii foz iguacu", "r d pedro ii foz iguacu parana", "r d pedro ii foz iguacu pr", "r d pedro ii parana", "r d pedro ii pr", "rua dom pedro ii", "rua dom pedro ii cen", "rua dom pedro ii cen foz do iguacu", "rua dom pedro ii cen foz do iguacu parana", "rua dom pedro ii cen foz do iguacu pr", "rua dom pedro ii cen foz iguacu", "rua dom pedro ii cen foz iguacu parana", "rua dom pedro ii cen foz iguacu pr", "rua dom pedro ii cen parana", "rua dom pedro ii cen pr", "rua dom pedro ii centro", "rua dom pedro ii centro foz do iguacu", "rua dom pedro ii centro foz do iguacu parana", "rua dom pedro ii centro foz do iguacu pr", "rua dom pedro ii centro foz iguacu", "rua dom pedro ii centro foz iguacu parana", "rua dom pedro ii centro foz iguacu pr", "rua dom pedro ii centro parana", "rua dom pedro ii centro pr", "rua dom pedro ii foz do iguacu", "rua dom pedro ii foz do iguacu parana", "rua dom pedro ii foz do iguacu pr", "rua dom pedro ii foz iguacu", "rua dom pedro ii foz iguacu parana", "rua dom pedro ii foz iguacu pr", "rua dom pedro ii parana", "rua dom pedro ii pr"])
  end
end
